name: Dockerized ASP.NET Core CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/callibrus-backend:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ../home/callibrus
          docker stop callibrus-backend || true
          docker rm callibrus-backend || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/callibrus-backend:latest
          docker run -d -p 8080:8080 --name callibrus-backend ${{ secrets.DOCKER_USERNAME }}/callibrus-backend:latest
